"""
Dagster pipeline for CarePulse Analytics.

Wires together the three stages of the project into a single asset graph:

    synthea_patient_data  -->  app_event_data  -->  raw_tables  -->  dbt_marts

- ``synthea_patient_data``: checks that Synthea CSVs have been generated
  (run ``src/data_generation/run_synthea.sh`` first -- this is a one-time,
  ~minutes-long download + simulation step that we don't want Dagster to
  repeat on every run).
- ``app_event_data``: re-runs ``simulate_app_events.py`` to (re)generate the
  simulated patient-app engagement CSVs (onboarding, sessions,
  notifications, appointments, medication logs).
- ``raw_tables``: loads all CSVs into the ``raw`` schema of the DuckDB
  warehouse via ``load_raw_to_duckdb.py``.
- ``dbt_marts``: runs ``dbt build`` (staging -> intermediate -> marts,
  plus all data tests) against that warehouse.

Run locally with:

    cd carepulse-analytics
    export DAGSTER_HOME=$(pwd)/.dagster_home   # optional, for run history
    dagster dev -f src/pipeline/dagster_assets.py

then click "Materialize all" in the Dagster UI, or use the
``carepulse_daily_pipeline`` schedule to run it automatically.
"""

import os
import subprocess
import sys
from pathlib import Path

import dagster as dg

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "data"
SYNTHEA_CSV_DIR = DATA_DIR / "synthea" / "csv"
APP_EVENTS_DIR = DATA_DIR / "app_events"
WAREHOUSE_DB_PATH = DATA_DIR / "warehouse.duckdb"
DBT_PROJECT_DIR = REPO_ROOT / "warehouse"

SIMULATE_SCRIPT = REPO_ROOT / "src" / "data_generation" / "simulate_app_events.py"
INGEST_SCRIPT = REPO_ROOT / "src" / "ingestion" / "load_raw_to_duckdb.py"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


class AppEventConfig(dg.Config):
    sim_days: int = 180
    seed: int = 42
    limit_patients: int = 0  # 0 means "no limit"


# ---------------------------------------------------------------------------
# Assets
# ---------------------------------------------------------------------------


@dg.asset(
    group_name="ingestion",
    description=(
        "Synthetic patient population generated by Synthea "
        "(data/synthea/csv/*.csv). This is a source asset checked for "
        "existence -- generate it once with src/data_generation/run_synthea.sh."
    ),
)
def synthea_patient_data() -> dg.MaterializeResult:
    required_files = ["patients.csv", "conditions.csv"]
    missing = [f for f in required_files if not (SYNTHEA_CSV_DIR / f).exists()]

    if missing:
        raise dg.Failure(
            description=(
                f"Missing Synthea CSVs in {SYNTHEA_CSV_DIR}: {missing}. "
                "Run `src/data_generation/run_synthea.sh` once to generate "
                "the synthetic patient population before materializing "
                "this pipeline."
            )
        )

    patient_count = sum(1 for _ in open(SYNTHEA_CSV_DIR / "patients.csv")) - 1
    return dg.MaterializeResult(
        metadata={
            "patients_csv": dg.MetadataValue.path(str(SYNTHEA_CSV_DIR / "patients.csv")),
            "patient_count": patient_count,
        }
    )


@dg.asset(
    group_name="ingestion",
    deps=[synthea_patient_data],
    description=(
        "Simulated patient app-engagement events (onboarding, sessions, "
        "notifications, appointments, medication logs), generated from the "
        "Synthea patient population."
    ),
)
def app_event_data(context: dg.AssetExecutionContext, config: AppEventConfig) -> dg.MaterializeResult:
    cmd = [
        sys.executable,
        str(SIMULATE_SCRIPT),
        "--synthea-dir", str(SYNTHEA_CSV_DIR),
        "--output-dir", str(APP_EVENTS_DIR),
        "--sim-days", str(config.sim_days),
        "--seed", str(config.seed),
    ]
    if config.limit_patients:
        cmd += ["--limit-patients", str(config.limit_patients)]

    context.log.info("Running: %s", " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    context.log.info(result.stdout)
    if result.returncode != 0:
        raise dg.Failure(description=f"simulate_app_events.py failed:\n{result.stderr}")

    output_files = sorted(p.name for p in APP_EVENTS_DIR.glob("*.csv"))
    return dg.MaterializeResult(
        metadata={
            "output_dir": dg.MetadataValue.path(str(APP_EVENTS_DIR)),
            "output_files": dg.MetadataValue.md("\n".join(f"- `{f}`" for f in output_files)),
            "sim_days": config.sim_days,
            "seed": config.seed,
        }
    )


@dg.asset(
    group_name="ingestion",
    deps=[app_event_data],
    description=(
        "Raw tables loaded into the `raw` schema of the DuckDB warehouse "
        "(one table per Synthea/app-event CSV)."
    ),
)
def raw_tables(context: dg.AssetExecutionContext) -> dg.MaterializeResult:
    cmd = [
        sys.executable,
        str(INGEST_SCRIPT),
        "--data-dir", str(DATA_DIR),
        "--db-path", str(WAREHOUSE_DB_PATH),
    ]
    context.log.info("Running: %s", " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    context.log.info(result.stdout)
    if result.returncode != 0:
        raise dg.Failure(description=f"load_raw_to_duckdb.py failed:\n{result.stderr}")

    return dg.MaterializeResult(
        metadata={
            "db_path": dg.MetadataValue.path(str(WAREHOUSE_DB_PATH)),
            "load_log": dg.MetadataValue.text(result.stdout),
        }
    )


@dg.asset(
    group_name="transformation",
    deps=[raw_tables],
    description=(
        "dbt staging -> intermediate -> marts models and all data tests, "
        "run against the DuckDB warehouse via `dbt build`."
    ),
)
def dbt_marts(context: dg.AssetExecutionContext) -> dg.MaterializeResult:
    env = os.environ.copy()
    env["DBT_PROFILES_DIR"] = str(DBT_PROJECT_DIR)
    env["CAREPULSE_DB_PATH"] = str(WAREHOUSE_DB_PATH)

    cmd = ["dbt", "build"]
    context.log.info("Running: %s (cwd=%s)", " ".join(cmd), DBT_PROJECT_DIR)
    result = subprocess.run(cmd, cwd=str(DBT_PROJECT_DIR), env=env, capture_output=True, text=True)
    context.log.info(result.stdout)
    if result.returncode != 0:
        raise dg.Failure(description=f"dbt build failed:\n{result.stdout}\n{result.stderr}")

    return dg.MaterializeResult(
        metadata={
            "db_path": dg.MetadataValue.path(str(WAREHOUSE_DB_PATH)),
            "dbt_log_tail": dg.MetadataValue.text("\n".join(result.stdout.splitlines()[-30:])),
        }
    )


# ---------------------------------------------------------------------------
# Jobs & schedules
# ---------------------------------------------------------------------------

carepulse_pipeline_job = dg.define_asset_job(
    name="carepulse_pipeline",
    selection=dg.AssetSelection.all(),
    description="Full pipeline: generate app events -> load raw tables -> dbt build.",
)

carepulse_daily_schedule = dg.ScheduleDefinition(
    name="carepulse_daily_pipeline",
    job=carepulse_pipeline_job,
    cron_schedule="0 6 * * *",  # 06:00 every day
    description="Regenerate simulated engagement data and rebuild the warehouse daily.",
)


defs = dg.Definitions(
    assets=[synthea_patient_data, app_event_data, raw_tables, dbt_marts],
    jobs=[carepulse_pipeline_job],
    schedules=[carepulse_daily_schedule],
)
